/*
 * Export.java
 *
 * Created on __DATE__, __TIME__
 */

package com.tanglover.communication.client;

import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author  __USER__
 */
public class Export extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String friendName;
	/** Creates new form Export */
	public Export(String friendName) {
		
		this.friendName = friendName;
		
		initComponents();
		
		URL url = this.getClass().getResource("/error.jpg");
		ImageIcon img = new ImageIcon(url);//���Ǳ���ͼƬ  
		JLabel imgLabel = new JLabel(img);//������ͼ���ڱ�ǩ�  

		Container cp = this.getContentPane();
		cp.add(imgLabel);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//ע�������ǹؼ�����������ǩ��ӵ�jfram��LayeredPane����  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());//���ñ�����ǩ��λ��  
		// this.setSize(800, 500);
		this.setVisible(true);

		((JPanel) getContentPane()).setOpaque(false); //ע����������������Ϊ͸��������LayeredPane����еı���������ʾ������ 

		this.setResizable(false);
		
		setLocation(((int)Toolkit.getDefaultToolkit().getScreenSize().getWidth()-750), 400);

		Toolkit tool = getToolkit(); //�õ�һ��Toolkit���� 
		URL url1 = this.getClass().getResource("/logoo.jpg");
		Image myimage = tool.getImage(url1); //��tool��ȡͼ�� 
		setIconImage(myimage);

		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				tuiChu();

			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u5bfc\u51fa\u6587\u4ef6\u6210\u529f\uff01");

		jButton1.setText("\u786e\u5b9a");

		jLabel2.setText("λ��D:\\ "+friendName+".txt");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(94,
						Short.MAX_VALUE).addComponent(jButton1).addGap(19, 19,
						19)).addGroup(
				layout.createSequentialGroup().addGap(25, 25, 25).addComponent(
						jLabel2).addContainerGap(13, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup().addContainerGap()
								.addComponent(jLabel1).addContainerGap(76,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(
						jLabel1).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7,
						Short.MAX_VALUE).addComponent(jLabel2).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton1).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public void tuiChu() {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new Export().setVisible(true);
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private JLabel jLabel1;
	private JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}