/*
 * FriendMessage.java
 *
 * Created on __DATE__, __TIME__
 */

package com.tanglover.communication.client;

import com.tanglover.communication.datadeal.UserInfoBean;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

/**
 *
 * @author  __USER__
 */
public class FriendMessage extends javax.swing.JFrame {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private UserInfoBean userInfoBean;

	/** Creates new form FriendMessage */
	public FriendMessage(UserInfoBean userInfoBean) {

		this.userInfoBean = userInfoBean;

		initComponents();

		URL url = this.getClass().getResource("/bb.jpg");
		ImageIcon img = new ImageIcon(url);//这是背景图片
		JLabel imgLabel = new JLabel(img);//将背景图放在标签里。

		Container cp = this.getContentPane();
		cp.add(imgLabel);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());//设置背景标签的位置
		// this.setSize(800, 500);
		this.setVisible(true);

		setLocation(((int)Toolkit.getDefaultToolkit().getScreenSize().getWidth()-950), 250);

		((JPanel) getContentPane()).setOpaque(false); //注意这里，将内容面板设为透明。这样LayeredPane面板中的背景才能显示出来。

		this.setResizable(false);

		Toolkit tool = getToolkit(); //得到一个Toolkit对象
		URL url1 = this.getClass().getResource("/logoo.jpg");
		Image myimage = tool.getImage(url1); //由tool获取图像
		setIconImage(myimage);

		//获取好友资料到页面显示。。。
		setUserInfo();
		//获取好友资料到页面显示。。。


		jTextArea1.setEditable(false);

		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				exit();

			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

//		ImageIcon image = new ImageIcon("src\\touxiang2.jpg");
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u597d\u53cb\u4fe1\u606f");

		jLabel2.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel2.setText("\u6635    \u79f0\uff1a");

		jLabel3.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel3.setText(null);

		jLabel4.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel4.setText("\u771f\u5b9e\u59d3\u540d\uff1a");

		jLabel5.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel5.setText(null);

		jLabel6.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel6.setText("\u6027    \u522b\uff1a");

		jLabel7.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel7.setText(null);

		jLabel8.setText("\u90e8     \u95e8\uff1a");

		jLabel9.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel9.setText(null);

		jLabel10.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel10.setText("\u5e38\u7528\u7535\u8bdd\uff1a");

		jLabel11.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel11.setText(null);

		jLabel12.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel12.setText("Email\uff1a");

		jLabel13.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel13.setText(null);

		jLabel14.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel14.setText("\u4e2a\u4eba\u8d44\u6599\uff1a");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setFont(new java.awt.Font("黑体", 0, 14));
		jButton1.setText("\u5173\u95ed");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				116,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				46,
																				46,
																				46)
																		.addComponent(
																				jLabel14)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				41,
																				41,
																				41)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel12)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addGap(
																												18,
																												18,
																												18)
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												93,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel4)
																														.addComponent(
																																jLabel8)
																														.addComponent(
																																jLabel6)
																														.addComponent(
																																jLabel10))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				26,
																																				26,
																																				26)
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel9)
																																						.addComponent(
																																								jLabel7)
																																						.addComponent(
																																								jLabel11)
																																						.addComponent(
																																								jLabel13,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								139,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				jLabel5)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				400,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(27, 27, 27)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										391, Short.MAX_VALUE).addComponent(
										jButton1).addGap(119, 119, 119)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								31,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5))
																		.addGap(
																				26,
																				26,
																				26)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel6))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel9)))
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																148,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel11)
														.addComponent(jLabel10))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel12)
														.addComponent(jLabel13))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				44,
																				44,
																				44)
																		.addComponent(
																				jLabel14,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				16,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				27,
																				27,
																				27)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				114,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												12, Short.MAX_VALUE)
										.addComponent(jButton1)
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public void exit() {
		this.dispose();
	}

	//打开好友资料窗口，把好友资料设进去，查看好友的资料
	public void setUserInfo() {
		UserInfoBean showFriendInfo = userInfoBean;

		URL url = this.getClass().getResource("/"+showFriendInfo.getTouXiang());

		ImageIcon image = new ImageIcon(url);
		jLabel1.setIcon(image);
		jLabel3.setText(showFriendInfo.getNichen());
		jLabel5.setText(showFriendInfo.getName());
		jLabel7.setText(showFriendInfo.getSex());
		jLabel9.setText(showFriendInfo.getPart());
		jLabel11.setText(showFriendInfo.getPhoneNum());
		jLabel13.setText(showFriendInfo.getEmail());
		jTextArea1.setText(showFriendInfo.getJianjie());

	}

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new FriendMessage().setVisible(true);
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}