package com.tanglover.communication.client;

/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	public String username;
	public String userpwd;
	public String userip;
	public String userport;
	public Socket s;

	/** Creates new form Login */
	public Login() {
		initComponents();

		URL url = this.getClass().getResource("/logo.jpg");
		ImageIcon img = new ImageIcon(url);//这是背景图片
		JLabel imgLabel = new JLabel(img);//将背景图放在标签里。

		Container cp = this.getContentPane();
		cp.add(imgLabel);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());//设置背景标签的位置

		this.setVisible(true);

		((JPanel) getContentPane()).setOpaque(false); //注意这里，将内容面板设为透明。这样LayeredPane面板中的背景才能显示出来。

		this.setResizable(false);

		Toolkit tool = getToolkit(); //得到一个Toolkit对象
		URL url1 = this.getClass().getResource("/logoo.jpg");
		Image myimage = tool.getImage(url1); //由tool获取图像
		setIconImage(myimage);

		jButton1.addActionListener(new Botton1());
		jButton2.addActionListener(new Botton2());
		setLocation(((int) Toolkit.getDefaultToolkit().getScreenSize()
				.getWidth() / 2 - 200), ((int) Toolkit.getDefaultToolkit()
				.getScreenSize().getHeight() / 2 - 200));

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u767b\u5f55");

		jTextField1.setForeground(new java.awt.Color(102, 102, 102));
		jTextField1.setText("c0001");
		jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel1.setFont(new java.awt.Font("新宋体", 0, 12));
		jLabel1.setForeground(new java.awt.Color(51, 153, 255));
		jLabel1.setText("\u8d26  \u53f7");
		jLabel1.setFocusCycleRoot(true);

		jLabel2.setFont(new java.awt.Font("新宋体", 0, 12));
		jLabel2.setForeground(new java.awt.Color(51, 153, 255));
		jLabel2.setText("\u5bc6  \u7801");
		jLabel2.setFocusCycleRoot(true);

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/etc/programe/loginphoto.gif"))); // NOI18N
		jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1,
				1));

		jButton1.setFont(new java.awt.Font("新宋体", 0, 12));
		jButton1.setForeground(new java.awt.Color(0, 0, 102));
		jButton1.setText("\u53d6\u6d88");

		jButton2.setFont(new java.awt.Font("新宋体", 0, 12));
		jButton2.setForeground(new java.awt.Color(0, 0, 102));
		jButton2.setText("\u767b\u5f55");

		jTextField3.setForeground(new java.awt.Color(51, 51, 51));
		jTextField3.setText("127.0.0.1");
		jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jTextField4.setForeground(new java.awt.Color(51, 51, 51));
		jTextField4.setText("9000");
		jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel4.setFont(new java.awt.Font("新宋体", 0, 12));
		jLabel4.setForeground(new java.awt.Color(51, 153, 255));
		jLabel4.setText("IP");
		jLabel4.setFocusCycleRoot(true);

		jLabel5.setFont(new java.awt.Font("新宋体", 0, 12));
		jLabel5.setForeground(new java.awt.Color(51, 153, 255));
		jLabel5.setText("\u7aef\u53e3\u53f7");
		jLabel5.setFocusCycleRoot(true);

		jPasswordField1.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				28,
																				28,
																				28)
																		.addComponent(
																				jButton2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton1))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jPasswordField1)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jTextField3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												91,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField4))
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								176,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								45,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel5))))
										.addContainerGap(14, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(122, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				21,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				12,
																				12,
																				12)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel4)
																		.addComponent(
																				jTextField4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel5))
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap())
						.addGroup(
								layout.createSequentialGroup().addGap(117, 117,
										117).addComponent(jLabel3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										82, Short.MAX_VALUE).addGap(39, 39, 39)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 功能实现
	 * @return
	 */
	//	得到用户输入的信息
	@SuppressWarnings("deprecation")
	public void userInformation() {
		username = jTextField1.getText();
		userpwd = jPasswordField1.getText();
		userip = jTextField3.getText();
		userport = jTextField4.getText();
	}

	//判断是否为空
	public void sure() {
		userInformation();
		ObjectInputStream ois = null;
		ObjectOutputStream oos = null;
		//与服务器相连

		Object readObject = null;
		try {
			s = new Socket(jTextField3.getText(), Integer.parseInt(jTextField4
					.getText()));
			String myIp1 = s.getLocalAddress().toString();
			String myIp = myIp1.substring(1);

			oos = new ObjectOutputStream(s.getOutputStream());
			CheckInfo check = new CheckInfo();
			check.setName(username);
			check.setPwd(userpwd);
			check.setMyIp(myIp);
			oos.writeObject(check);

			ois = new ObjectInputStream(s.getInputStream());
			readObject = ois.readObject();
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (username.equals("") || userpwd.equals("") || userip.equals("")
				|| userport.equals("")) {
			String str2 = "你的输入不合法！";
			new Error(str2);
		} else if (readObject instanceof ServerToClient) {
			new ClieneMainFrame(s, username, readObject);
			this.dispose();
		} else if (readObject == null) {
			String str1 = "你输入的密码错误！";
			new Error(str1);
		}

	}

	//确认键监听
	public class Botton2 implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
			sure();
		}

	}

	//取消键监听
	public class Botton1 implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
			System.exit(0);
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

}