/*
 * MyMessage.java
 *
 * Created on __DATE__, __TIME__
 */

package com.tanglover.communication.client;

import com.tanglover.communication.datadeal.UserInfoBean;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.URL;

/**
 * 
 * @author __USER__
 */
public class PersonnerMessage extends javax.swing.JFrame {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private UserInfoBean userInfoBean;

	/** Creates new form MyMessage */
	public PersonnerMessage(UserInfoBean userInfoBean, final Socket s) {

		this.userInfoBean = userInfoBean;
		initComponents();

		URL url = this.getClass().getResource("/bb.jpg");
		ImageIcon img = new ImageIcon(url);// 这是背景图片
		JLabel imgLabel = new JLabel(img);// 将背景图放在标签里。

		Container cp = this.getContentPane();
		cp.add(imgLabel);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));// 注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());// 设置背景标签的位置
		// this.setSize(800, 500);
		this.setVisible(true);

		((JPanel) getContentPane()).setOpaque(false); // 注意这里，将内容面板设为透明。这样LayeredPane面板中的背景才能显示出来。

		this.setResizable(false);

		setLocation(((int) Toolkit.getDefaultToolkit().getScreenSize()
				.getWidth() - 950), 250);

		Toolkit tool = getToolkit(); // 得到一个Toolkit对象
		URL url1 = this.getClass().getResource("/logoo.jpg");
		Image myimage = tool.getImage(url1); //由tool获取图像
		setIconImage(myimage);
		// 打开自己的资料窗口，就可从服务器获得自己的资料
		getMyInfo();

		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				exit();

			}
		});

		jButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				UserInfoBean writeUser = myInfo();
				if (writeUser == null) {
					return;
				} else {
					ObjectOutputStream oos;
					try {
						oos = new ObjectOutputStream(s.getOutputStream());
						oos.writeObject(writeUser);
						oos.flush();
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}

					exit();
				}
			}
		});

		// 初始化时文本不可编辑
		jTextField1.setEditable(false);
		jTextField2.setEditable(false);
		jTextField3.setEditable(false);
		jTextField4.setEditable(false);
		jTextField5.setEditable(false);
		jTextField6.setEditable(false);
		jTextArea1.setEditable(false);
		jComboBox1.setEditable(false);
		jComboBox2.setEditable(false);
		jButton2.setEnabled(false);

		// 设置性别不可双选
		ButtonGroup bg = new ButtonGroup();
		bg.add(jRadioButton1);
		bg.add(jRadioButton2);

		jRadioButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				// sex = "男";
			}
		});

		jRadioButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				// sex = "女";
			}
		});

		jButton4.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				change();

			}
		});

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		image = new ImageIcon("src\\tx1.jpg");
		new ImageIcon("src\\1.jpg");
		new ImageIcon("src\\2.jpg");
		new ImageIcon("src\\3.jpg");
		jLabel1 = new javax.swing.JLabel(image);
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JPasswordField();
		jLabel5 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JPasswordField();
		jLabel6 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jLabel7 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel8 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jComboBox2 = new javax.swing.JComboBox();
		jButton4 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u4e2a\u4eba\u8d44\u6599");

		jLabel1.setText("");

		jLabel2.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel2.setText("\u6635\u79f0\uff1a");

		jLabel3.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel3.setText("\u771f\u5b9e\u59d3\u540d\uff1a");

		jLabel4.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel4.setText("\u5bc6\u7801\uff1a");

		jLabel5.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel5.setText("\u786e\u8ba4\u5bc6\u7801\uff1a");

		jLabel6.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel6.setText("\u6027\u522b\uff1a");

		jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
		jRadioButton1.setFont(new java.awt.Font("黑体", 0, 14));
		jRadioButton1.setText("\u7537");

		jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
		jRadioButton2.setFont(new java.awt.Font("黑体", 0, 14));
		jRadioButton2.setText("\u5973");

		jLabel7.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel7.setText("\u90e8\u95e8\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { changePart() }));

		jLabel8.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel8.setText("\u5e38\u7528\u7535\u8bdd\uff1a");

		jLabel9.setText("Email:");

		jLabel10.setFont(new java.awt.Font("黑体", 0, 14));
		jLabel10.setText("个人简介");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("\u53d6\u6d88");

		jButton2.setText("\u786e\u5b9a");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"1.png", "2.png", "3.png", "4.png", "5.png", "6.png", "7.png",
				"8.png", "9.png", "10.png" }));

		jButton4.setText("\u4fee\u6539");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(
																												jLabel10)
																										.addComponent(
																												jLabel1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												98,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												8,
																												8,
																												8)
																										.addComponent(
																												jComboBox2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												70,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												33,
																												33,
																												33)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel4)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																						.addComponent(
																																								jTextField3,
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel2,
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jTextField1,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												143,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addGap(
																																												65,
																																												65,
																																												65)
																																										.addComponent(
																																												jLabel3))
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addGap(
																																												64,
																																												64,
																																												64)
																																										.addGroup(
																																												layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING,
																																																false)
																																														.addComponent(
																																																jLabel5)
																																														.addComponent(
																																																jTextField4)
																																														.addComponent(
																																																jTextField2,
																																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																																146,
																																																javax.swing.GroupLayout.PREFERRED_SIZE)
																																														.addGroup(
																																																layout
																																																		.createSequentialGroup()
																																																		.addComponent(
																																																				jLabel7)
																																																		.addPreferredGap(
																																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																																		.addComponent(
																																																				jComboBox1,
																																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																																				javax.swing.GroupLayout.PREFERRED_SIZE))))))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel6)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																										.addComponent(
																																												jRadioButton1))
																																						.addGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								layout
																																										.createSequentialGroup()
																																										.addGap(
																																												4,
																																												4,
																																												4)
																																										.addGroup(
																																												layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING)
																																														.addGroup(
																																																layout
																																																		.createSequentialGroup()
																																																		.addComponent(
																																																				jLabel9)
																																																		.addPreferredGap(
																																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																																														.addComponent(
																																																jLabel8,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																Short.MAX_VALUE))))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								false)
																																						.addComponent(
																																								jRadioButton2)
																																						.addComponent(
																																								jTextField5,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								224,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								jTextField6)))))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												382,
																												Short.MAX_VALUE)))
																		.addGap(
																				59,
																				59,
																				59))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton4)
																		.addGap(
																				36,
																				36,
																				36)
																		.addComponent(
																				jButton2)
																		.addGap(
																				37,
																				37,
																				37)
																		.addComponent(
																				jButton1)
																		.addGap(
																				87,
																				87,
																				87)))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																104,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jRadioButton1)
														.addComponent(
																jRadioButton2)
														.addComponent(jLabel7)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																27,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel10)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																82,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												11, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton2)
														.addComponent(jButton4))
										.addContainerGap()));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	// 修改资料
	public void change() {
		jTextField1.setEditable(true);
		// jTextField2.setEditable(true);
		jTextField3.setEditable(true);
		jTextField4.setEditable(true);
		jTextField5.setEditable(true);
		jTextField6.setEditable(true);
		jTextArea1.setEditable(true);
		// jComboBox1.setEditable(true);
		jComboBox2.setEditable(true);
		jButton2.setEnabled(true);
		jButton4.setEnabled(false);

		jComboBox2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				String str = "src\\" + jComboBox2.getSelectedItem();
				ImageIcon ima = new ImageIcon(str);
				jLabel1.setIcon(ima);

			}
		});
	}

	public void exit() {
		this.dispose();
	}

	// 把自己改后的信息封装好可以发给服务器
	@SuppressWarnings("deprecation")
	public static UserInfoBean myInfo() {
		String nichen = jTextField1.getText();
		String name = jTextField2.getText();
		String pwd = null;
		String pwd2 = jTextField4.getText();
		String pwd1 = jTextField3.getText();
		if (!pwd2.equals(pwd1)) {
			new PwdError();

		} else {
			pwd = pwd1;
			String phonenum = jTextField5.getText();
			String mail = jTextField6.getText();
			String touxiang = (String) jComboBox2.getSelectedItem();
			String jianjie = jTextArea1.getText();
			if (jRadioButton1.isSelected()) {
				sex = "男";
			} else {
				sex = "女";
			}

			UserInfoBean userInfo = new UserInfoBean();
			userInfo.setNichen(nichen);
			userInfo.setName(name);
			userInfo.setPassword(pwd);
			userInfo.setPhoneNum(phonenum);
			userInfo.setEmail(mail);
			userInfo.setSex(sex);
			userInfo.setTouXiang(touxiang);
			userInfo.setJianjie(jianjie);
			userInfo.setPart(jComboBox1.getSelectedItem().toString());

			return userInfo;
		}
		return null;

	}

	// 从服务器取得资料
	public void getMyInfo() {

		UserInfoBean myInfo = userInfoBean;

		URL url = this.getClass().getResource("/"+myInfo.getTouXiang());

//		String imageName = "src\\" + myInfo.getTouXiang();
		ImageIcon imag = new ImageIcon(url);
		jLabel1.setIcon(imag);

		jTextField1.setText(myInfo.getNichen());
		jTextField2.setText(myInfo.getName());
		jTextField3.setText(myInfo.getPassword());
		jTextField4.setText(myInfo.getPassword());
		jTextField5.setText(myInfo.getPhoneNum());
		jTextField6.setText(myInfo.getEmail());
		jTextArea1.setText(myInfo.getJianjie());

		String ssex = myInfo.getSex();
		if (ssex.equals("男")) {
			jRadioButton1.setSelected(true);
		} else {
			jRadioButton2.setSelected(true);
		}

	}

	public String changePart() {
		String ppart = userInfoBean.getPart();
		return ppart;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	// public static void main(String args[]) {
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new PersonnerMessage().setVisible(true);
	// }
	// });
	//
	// }

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton4;
	public static JComboBox jComboBox1;
	public static JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	public static JRadioButton jRadioButton1;
	public static JRadioButton jRadioButton2;
	private javax.swing.JScrollPane jScrollPane1;
	public static JTextArea jTextArea1;
	public static JTextField jTextField1;
	public static JTextField jTextField2;
	public static JPasswordField jTextField3;
	public static JPasswordField jTextField4;
	public static JTextField jTextField5;
	public static JTextField jTextField6;
	private ImageIcon image;
	public static String sex;

}