/*
 * Error.java
 *
 * Created on __DATE__, __TIME__
 */

package com.tanglover.communication.client;

import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author  __USER__
 */
public class PwdError extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Error */
	public PwdError() {
		initComponents();
		
		this.setTitle("��ʾ");
		setLocation(500, 400);
		
		URL url = this.getClass().getResource("/error.jpg");
		ImageIcon img = new ImageIcon(url);//���Ǳ���ͼƬ  
		JLabel imgLabel = new JLabel(img);//������ͼ���ڱ�ǩ�  

		Container cp = this.getContentPane();
		cp.add(imgLabel);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//ע�������ǹؼ�����������ǩ��ӵ�jfram��LayeredPane����  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());//���ñ�����ǩ��λ��  
		// this.setSize(800, 500);
		this.setVisible(true);

		((JPanel) getContentPane()).setOpaque(false); //ע����������������Ϊ͸��������LayeredPane����еı���������ʾ������ 

		this.setResizable(false);

		Toolkit tool = getToolkit(); //�õ�һ��Toolkit���� 
		URL url1 = this.getClass().getResource("/logoo.jpg");
		Image myimage = tool.getImage(url1); //��tool��ȡͼ�� 
		setIconImage(myimage);
		
		setLocation(((int)Toolkit.getDefaultToolkit().getScreenSize().getWidth()-750), 400);

		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				tuiChu();

			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("����", 0, 14));
		jLabel1.setForeground(new java.awt.Color(153, 0, 0));
		jLabel1.setIcon(new ImageIcon(getClass().getResource(
				"/javax/swing/plaf/metal/icons/Warn.gif"))); // NOI18N
		jLabel1
				.setText("\u4e24\u6b21\u5bc6\u7801\u8f93\u5165\u4e0d\u4e00\u81f4\uff01");

		jButton1.setFont(new java.awt.Font("����", 0, 14));
		jButton1.setText("\u786e\u5b9a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(78,
								Short.MAX_VALUE).addComponent(jButton1).addGap(
								37, 37, 37)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						jLabel1).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jButton1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 17,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jLabel1.getAccessibleContext().setAccessibleName(
				"\u5bc6\u7801\u9519\u8bef\u6216\u91cd\u590d\u767b\u5f55");

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public void tuiChu() {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
//		public static void main(String args[]) {
//			java.awt.EventQueue.invokeLater(new Runnable() {
//				public void run() {
//					new PwdError().setVisible(true);
//				}
//			});
//		}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}